package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* lundi 20 janvier 2025 00 h 44 CET
*/

public interface HelloOperations 
{
  String sayHello ();
} // interface HelloOperations
