module HelloApp {
    interface Hello {
        float addition(in float a, in float b);
        float soustraction(in float a, in float b);
        float multiplication(in float a, in float b);
        float division(in float a, in float b);

        void createFile(in string content);
        string readFile();

        // Méthode pour enregistrer un client
        string registerClient();
    };
};
