package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* vendredi 17 janvier 2025 15 h 32 CET
*/

public interface HelloOperations 
{
  String sayHello ();
} // interface HelloOperations
