package HelloApp;


/**
* HelloApp/HelloPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* mardi 21 janvier 2025 12 h 16 GMT+02:00
*/

public abstract class HelloPOA extends org.omg.PortableServer.Servant
 implements HelloApp.HelloOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("addition", new java.lang.Integer (0));
    _methods.put ("soustraction", new java.lang.Integer (1));
    _methods.put ("multiplication", new java.lang.Integer (2));
    _methods.put ("division", new java.lang.Integer (3));
    _methods.put ("createFile", new java.lang.Integer (4));
    _methods.put ("readFile", new java.lang.Integer (5));
    _methods.put ("registerClient", new java.lang.Integer (6));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // HelloApp/Hello/addition
       {
         float a = in.read_float ();
         float b = in.read_float ();
         float $result = (float)0;
         $result = this.addition (a, b);
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 1:  // HelloApp/Hello/soustraction
       {
         float a = in.read_float ();
         float b = in.read_float ();
         float $result = (float)0;
         $result = this.soustraction (a, b);
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 2:  // HelloApp/Hello/multiplication
       {
         float a = in.read_float ();
         float b = in.read_float ();
         float $result = (float)0;
         $result = this.multiplication (a, b);
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 3:  // HelloApp/Hello/division
       {
         float a = in.read_float ();
         float b = in.read_float ();
         float $result = (float)0;
         $result = this.division (a, b);
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 4:  // HelloApp/Hello/createFile
       {
         String content = in.read_string ();
         this.createFile (content);
         out = $rh.createReply();
         break;
       }

       case 5:  // HelloApp/Hello/readFile
       {
         String $result = null;
         $result = this.readFile ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }


  // Méthode pour enregistrer un client
       case 6:  // HelloApp/Hello/registerClient
       {
         String $result = null;
         $result = this.registerClient ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:HelloApp/Hello:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Hello _this() 
  {
    return HelloHelper.narrow(
    super._this_object());
  }

  public Hello _this(org.omg.CORBA.ORB orb) 
  {
    return HelloHelper.narrow(
    super._this_object(orb));
  }


} // class HelloPOA
