package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* mardi 21 janvier 2025 12 h 16 GMT+02:00
*/

public interface HelloOperations 
{
  float addition (float a, float b);
  float soustraction (float a, float b);
  float multiplication (float a, float b);
  float division (float a, float b);
  void createFile (String content);
  String readFile ();

  // Méthode pour enregistrer un client
  String registerClient ();
} // interface HelloOperations
